# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('date', models.DateField(auto_now=True)),
                ('essential', models.BooleanField(default=False)),
                ('is_expense', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Category')),
            ],
        ),
    ]
