# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 28, 20, 50, 5, 758540, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
