# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20160403_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='is_expense',
        ),
        migrations.AddField(
            model_name='entry',
            name='flow_type',
            field=models.CharField(choices=[(b'income', b'Income'), (b'expense', b'Expense')], default=b'expense', max_length=50),
        ),
    ]
