# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_entry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
