# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-06 16:02
from __future__ import unicode_literals

from django.db import migrations

'''
This migration creates the oAuth2 Application for google to follow the authorization code flow.
'''


def create_google_application(apps, schema_editor):
    # Application = apps.get_model('oauth2_provider', 'Application')
    from oauth2_provider.models import Application

    application = Application(
        client_id = '4O9vihRrTRAlwcSOJjLxgZgtvWq5ZT4UQzc3NXYx',
        client_secret = 'QG9uGNUQy6lvGhSYRwkPFban14UMi3juWVw8Y5aV9pOaDdRXIWW4Q7TbuQdvcrnTgbqOn6PPgYKapbr8gIAoCOFoBWimmWjJvHhQI2y2TQBh7DoI1bZfxTVyxH3pM2Iv',
        name = 'google',
        redirect_uris = 'https://oauth-redirect.googleusercontent.com/r/budgie-bf791',
    )
    application.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_google_application),
    ]
